-- Supabase Schema: lin

-- Users table (extends Supabase auth.users)
create table if not exists public.users (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  name        text,
  avatar_url  text,
  created_at  timestamptz not null default now()
);

alter table public.users enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can read all users') then
    create policy "Users can read all users" on public.users for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can insert their own record') then
    create policy "Users can insert their own record" on public.users for insert with check (auth.uid() = id);
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can update their own record') then
    create policy "Users can update their own record" on public.users for update using (auth.uid() = id);
  end if;
end;
$$;

-- Auto-create public.users row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_user();
  end if;
end;
$$;

-- Look up email by nickname for sign-in
create or replace function public.get_email_by_nickname(nickname text)
returns text
language sql
stable
security definer
as $$
  select email from public.users where name = nickname limit 1;
$$;

-- create_local_user was removed — use /api/create-user or Supabase Dashboard instead
-- (direct auth.users inserts are incompatible with this Supabase version)

do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_status') then
    create type issue_status as enum ('backlog', 'todo', 'in_progress', 'done', 'canceled');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_priority') then
    create type issue_priority as enum ('none', 'low', 'medium', 'high', 'urgent');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_team') then
    create type issue_team as enum ('ART', 'DEV', 'QA', 'GD', 'Sound');
  end if;
end;
$$;

create table if not exists public.issues (
  id             bigint generated by default as identity primary key,
  title          text not null,
  description    text,
  status         issue_status not null default 'backlog',
  priority       issue_priority not null default 'none',
  team           issue_team,
  is_epic        boolean not null default false,
  parent_epic_id bigint references public.issues(id) on delete set null,
  due_date       date,
  assignee_id    uuid references public.users(id) on delete set null,
  created_by     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Auto-update updated_at
create extension if not exists moddatetime schema extensions;
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'issues_updated_at'
  ) then
    create trigger issues_updated_at
      before update on public.issues
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;

alter table public.issues enable row level security;

-- Row Level Security: users can see all issues, update only ones they created or are assigned
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can view all issues'
  ) then
    create policy "Users can view all issues" on public.issues for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can create issues'
  ) then
    drop policy if exists "Users can create issues" on public.issues;
    create policy "Users can create issues" on public.issues for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can update issues'
  ) then
    drop policy if exists "Users can update their own issues or assigned issues" on public.issues;
    create policy "Users can update issues" on public.issues for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can delete issues'
  ) then
    drop policy if exists "Users can delete their own issues" on public.issues;
    create policy "Users can delete issues" on public.issues for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Linked PRs / issues from GitHub
create table if not exists public.issue_links (
  id        bigint generated by default as identity primary key,
  issue_id  bigint not null references public.issues(id) on delete cascade,
  pr_url    text not null,
  pr_title  text not null,
  pr_state  text not null default 'open',
  created_at timestamptz not null default now()
);

alter table public.issue_links enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_links' and policyname = 'Users can read issue_links') then
    create policy "Users can read issue_links" on public.issue_links for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_links' and policyname = 'Users can insert issue_links') then
    create policy "Users can insert issue_links" on public.issue_links for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Milestones
create table if not exists public.milestones (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  target_date date,
  created_at  timestamptz not null default now()
);

alter table public.milestones enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can read milestones') then
    create policy "Users can read milestones" on public.milestones for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can insert milestones') then
    create policy "Users can insert milestones" on public.milestones for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can update milestones') then
    create policy "Users can update milestones" on public.milestones for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can delete milestones') then
    create policy "Users can delete milestones" on public.milestones for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Add milestone_id to issues
do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'issues' and column_name = 'milestone_id') then
    alter table public.issues add column milestone_id bigint references public.milestones(id) on delete set null;
  end if;
end;
$$;

-- Indexes
create index if not exists idx_issues_status on public.issues(status);
create index if not exists idx_issues_priority on public.issues(priority);
create index if not exists idx_issues_assignee on public.issues(assignee_id);
create index if not exists idx_issues_created_by on public.issues(created_by);
create index if not exists idx_issues_created_at on public.issues(created_at desc);
create index if not exists idx_issues_milestone on public.issues(milestone_id);
