-- Supabase Schema: lin

-- Users table (extends Supabase auth.users)
create table if not exists public.users (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text not null,
  name        text,
  avatar_url  text,
  created_at  timestamptz not null default now()
);

alter table public.users enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can read all users') then
    create policy "Users can read all users" on public.users for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can insert their own record') then
    create policy "Users can insert their own record" on public.users for insert with check (auth.uid() = id);
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'users' and policyname = 'Users can update their own record') then
    create policy "Users can update their own record" on public.users for update using (auth.uid() = id);
  end if;
end;
$$;

-- Auto-create public.users row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute function public.handle_new_user();
  end if;
end;
$$;

-- Look up email by nickname for sign-in
create or replace function public.get_email_by_nickname(nickname text)
returns text
language sql
stable
security definer
as $$
  select email from public.users where name = nickname limit 1;
$$;

-- create_local_user was removed — use /api/create-user or Supabase Dashboard instead
-- (direct auth.users inserts are incompatible with this Supabase version)

do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_status') then
    create type issue_status as enum ('backlog', 'todo', 'in_progress', 'done', 'canceled');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_priority') then
    create type issue_priority as enum ('none', 'low', 'medium', 'high', 'urgent');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_type where typname = 'issue_team') then
    create type issue_team as enum ('3D', 'Concept', 'DEV', 'QA', 'GD', 'Sound');
  end if;
end;
$$;

create table if not exists public.projects (
  id          bigint generated by default as identity primary key,
  name        text not null,
  code        text not null unique,
  created_at  timestamptz not null default now()
);

alter table public.projects enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'projects' and policyname = 'Users can read projects') then
    create policy "Users can read projects" on public.projects for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'projects' and policyname = 'Users can create projects') then
    create policy "Users can create projects" on public.projects for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'projects' and policyname = 'Users can update projects') then
    create policy "Users can update projects" on public.projects for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'projects' and policyname = 'Users can delete projects') then
    create policy "Users can delete projects" on public.projects for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Default project
insert into public.projects (name, code) values ('DefaultProject', 'DEF') on conflict (code) do nothing;

create table if not exists public.issues (
  id             bigint generated by default as identity primary key,
  title          text not null,
  description    text,
  status         issue_status not null default 'backlog',
  priority       issue_priority not null default 'none',
  team           issue_team,
  is_epic        boolean not null default false,
  parent_epic_id bigint references public.issues(id) on delete set null,
  due_date       date,
  assignee_id    uuid references public.users(id) on delete set null,
  created_by     text,
  project_id     bigint references public.projects(id) on delete cascade,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- Auto-update updated_at
create extension if not exists moddatetime schema extensions;
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'issues_updated_at'
  ) then
    create trigger issues_updated_at
      before update on public.issues
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;

-- Per-project sequential issue number
alter table public.issues add column if not exists display_id integer;

create or replace function public.set_display_id()
returns trigger as $$
begin
  new.display_id = coalesce((select max(display_id) from public.issues where project_id = new.project_id), 0) + 1;
  return new;
end;
$$ language plpgsql;

drop trigger if exists issues_set_display_id on public.issues;
create trigger issues_set_display_id
  before insert on public.issues
  for each row
  when (new.display_id is null)
  execute function public.set_display_id();

alter table public.issues enable row level security;

-- Row Level Security: users can see all issues, update only ones they created or are assigned
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can view all issues'
  ) then
    create policy "Users can view all issues" on public.issues for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can create issues'
  ) then
    drop policy if exists "Users can create issues" on public.issues;
    create policy "Users can create issues" on public.issues for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can update issues'
  ) then
    drop policy if exists "Users can update their own issues or assigned issues" on public.issues;
    create policy "Users can update issues" on public.issues for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'issues' and policyname = 'Users can delete issues'
  ) then
    drop policy if exists "Users can delete their own issues" on public.issues;
    create policy "Users can delete issues" on public.issues for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Linked PRs / issues from GitHub
create table if not exists public.issue_links (
  id        bigint generated by default as identity primary key,
  issue_id  bigint not null references public.issues(id) on delete cascade,
  pr_url    text not null,
  pr_title  text not null,
  pr_state  text not null default 'open',
  created_at timestamptz not null default now()
);

alter table public.issue_links enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_links' and policyname = 'Users can read issue_links') then
    create policy "Users can read issue_links" on public.issue_links for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_links' and policyname = 'Users can insert issue_links') then
    create policy "Users can insert issue_links" on public.issue_links for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Milestones
create table if not exists public.milestones (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  target_date date,
  project_id  bigint references public.projects(id) on delete cascade,
  created_at  timestamptz not null default now()
);

alter table public.milestones enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can read milestones') then
    create policy "Users can read milestones" on public.milestones for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can insert milestones') then
    create policy "Users can insert milestones" on public.milestones for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can update milestones') then
    create policy "Users can update milestones" on public.milestones for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'milestones' and policyname = 'Users can delete milestones') then
    create policy "Users can delete milestones" on public.milestones for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

-- Add milestone_id to issues
do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'issues' and column_name = 'milestone_id') then
    alter table public.issues add column milestone_id bigint references public.milestones(id) on delete set null;
  end if;
end;
$$;

-- Add attachments (image/file metadata) to issues
do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'issues' and column_name = 'attachments') then
    alter table public.issues add column attachments jsonb not null default '[]'::jsonb;
  end if;
end;
$$;

-- Migrate existing text[] attachments (URL strings) to jsonb metadata objects
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'issues' and column_name = 'attachments' and data_type = 'ARRAY'
  ) then
    alter table public.issues alter column attachments drop default;
    alter table public.issues alter column attachments type jsonb
      using coalesce(to_jsonb(attachments), '[]'::jsonb);
    update public.issues
    set attachments = (
      select coalesce(jsonb_agg(jsonb_build_object('url', v, 'name', null, 'type', null)), '[]'::jsonb)
      from jsonb_array_elements_text(attachments) as t(v)
    )
    where jsonb_array_length(attachments) > 0
      and jsonb_typeof(attachments->0) = 'string';
    alter table public.issues alter column attachments set default '[]'::jsonb;
  end if;
end;
$$;

-- Indexes
create index if not exists idx_issues_status on public.issues(status);
create index if not exists idx_issues_priority on public.issues(priority);
create index if not exists idx_issues_assignee on public.issues(assignee_id);
create index if not exists idx_issues_created_by on public.issues(created_by);
create index if not exists idx_issues_created_at on public.issues(created_at desc);
create index if not exists idx_issues_milestone on public.issues(milestone_id);
create index if not exists idx_issues_project on public.issues(project_id);
create index if not exists idx_milestones_project on public.milestones(project_id);

-- Timeline entries (per-project issue placements on the timeline)
create table if not exists public.timeline_entries (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects(id) on delete cascade,
  issue_id    bigint not null references public.issues(id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  color       text,
  position    integer not null default 0,
  created_at  timestamptz not null default now(),
  unique (project_id, issue_id)
);

alter table public.timeline_entries enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'timeline_entries' and policyname = 'Users can read timeline_entries') then
    create policy "Users can read timeline_entries" on public.timeline_entries for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'timeline_entries' and policyname = 'Users can insert timeline_entries') then
    create policy "Users can insert timeline_entries" on public.timeline_entries for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'timeline_entries' and policyname = 'Users can update timeline_entries') then
    create policy "Users can update timeline_entries" on public.timeline_entries for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'timeline_entries' and policyname = 'Users can delete timeline_entries') then
    create policy "Users can delete timeline_entries" on public.timeline_entries for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_timeline_entries_project on public.timeline_entries(project_id);
create index if not exists idx_timeline_entries_issue on public.timeline_entries(issue_id);

-- Project membership: controls which projects a user can see.
-- A user with at least one membership sees ONLY those projects.
-- A user with NO memberships sees ALL projects (safe default for admins).
create table if not exists public.project_members (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references public.users(id) on delete cascade,
  project_id  bigint not null references public.projects(id) on delete cascade,
  role        text not null default 'member',
  name        text,
  department  text,
  created_at  timestamptz not null default now(),
  unique (user_id, project_id)
);

alter table public.project_members enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'project_members' and policyname = 'Users can read project_members') then
    create policy "Users can read project_members" on public.project_members for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'project_members' and policyname = 'Users can insert project_members') then
    create policy "Users can insert project_members" on public.project_members for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'project_members' and policyname = 'Users can update project_members') then
    create policy "Users can update project_members" on public.project_members for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'project_members' and policyname = 'Users can delete project_members') then
    create policy "Users can delete project_members" on public.project_members for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_project_members_user on public.project_members(user_id);
create index if not exists idx_project_members_project on public.project_members(project_id);

-- Documentation sections (hierarchical folders for docs)
create table if not exists public.doc_sections (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects(id) on delete cascade,
  parent_id   bigint references public.doc_sections(id) on delete cascade,
  name        text not null,
  color       text,
  position    integer not null default 0,
  created_at  timestamptz not null default now()
);

alter table public.doc_sections enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'doc_sections' and policyname = 'Authenticated can read doc_sections') then
    create policy "Authenticated can read doc_sections" on public.doc_sections for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'doc_sections' and policyname = 'Authenticated can insert doc_sections') then
    create policy "Authenticated can insert doc_sections" on public.doc_sections for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'doc_sections' and policyname = 'Authenticated can update doc_sections') then
    create policy "Authenticated can update doc_sections" on public.doc_sections for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'doc_sections' and policyname = 'Authenticated can delete doc_sections') then
    create policy "Authenticated can delete doc_sections" on public.doc_sections for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_doc_sections_project on public.doc_sections(project_id);
create index if not exists idx_doc_sections_parent on public.doc_sections(parent_id);

-- Documentation pages (markdown documents)
create table if not exists public.documents (
  id          bigint generated by default as identity primary key,
  project_id  bigint not null references public.projects(id) on delete cascade,
  section_id  bigint references public.doc_sections(id) on delete set null,
  title       text not null default 'Untitled',
  content     text not null default '',
  position    integer not null default 0,
  created_by  uuid references public.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.documents enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Authenticated can read documents') then
    create policy "Authenticated can read documents" on public.documents for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Authenticated can insert documents') then
    create policy "Authenticated can insert documents" on public.documents for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Authenticated can update documents') then
    create policy "Authenticated can update documents" on public.documents for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'documents' and policyname = 'Authenticated can delete documents') then
    create policy "Authenticated can delete documents" on public.documents for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_documents_project on public.documents(project_id);
create index if not exists idx_documents_section on public.documents(section_id);

-- Auto-update updated_at on documents
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'documents_updated_at'
  ) then
    create trigger documents_updated_at
      before update on public.documents
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;

create table if not exists public.issue_comments (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues(id) on delete cascade,
  content text not null,
  author_id uuid references public.users(id) on delete set null,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.issue_comments enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can read issue_comments') then
    create policy "Users can read issue_comments" on public.issue_comments for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can insert issue_comments') then
    create policy "Users can insert issue_comments" on public.issue_comments for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can update issue_comments') then
    create policy "Users can update issue_comments" on public.issue_comments for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can delete issue_comments') then
    create policy "Users can delete issue_comments" on public.issue_comments for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_issue_comments_issue on public.issue_comments(issue_id);

-- Auto-update updated_at on issue_comments
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'issue_comments_updated_at'
  ) then
    create trigger issue_comments_updated_at
      before update on public.issue_comments
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;

create table if not exists public.issue_comments (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues(id) on delete cascade,
  content text not null,
  author_id uuid references public.users(id) on delete set null,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.issue_comments enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can read issue_comments') then
    create policy "Users can read issue_comments" on public.issue_comments for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can insert issue_comments') then
    create policy "Users can insert issue_comments" on public.issue_comments for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can update issue_comments') then
    create policy "Users can update issue_comments" on public.issue_comments for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can delete issue_comments') then
    create policy "Users can delete issue_comments" on public.issue_comments for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_issue_comments_issue on public.issue_comments(issue_id);

-- Auto-update updated_at on issue_comments
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'issue_comments_updated_at'
  ) then
    create trigger issue_comments_updated_at
      before update on public.issue_comments
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;
