create table if not exists public.issue_dependencies (
  id            bigint generated by default as identity primary key,
  issue_id      bigint not null references public.issues(id) on delete cascade,
  blocked_by_id bigint not null references public.issues(id) on delete cascade,
  created_at    timestamptz not null default now(),
  unique (issue_id, blocked_by_id)
);

alter table public.issue_dependencies enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_dependencies' and policyname = 'Users can read issue_dependencies') then
    create policy "Users can read issue_dependencies" on public.issue_dependencies for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_dependencies' and policyname = 'Users can insert issue_dependencies') then
    create policy "Users can insert issue_dependencies" on public.issue_dependencies for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_dependencies' and policyname = 'Users can delete issue_dependencies') then
    create policy "Users can delete issue_dependencies" on public.issue_dependencies for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_issue_dependencies_issue on public.issue_dependencies(issue_id);
create index if not exists idx_issue_dependencies_blocked_by on public.issue_dependencies(blocked_by_id);
