create table if not exists public.issue_comments (
  id bigint generated by default as identity primary key,
  issue_id bigint not null references public.issues(id) on delete cascade,
  content text not null,
  author_id uuid references public.users(id) on delete set null,
  author_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.issue_comments enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can read issue_comments') then
    create policy "Users can read issue_comments" on public.issue_comments for select using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can insert issue_comments') then
    create policy "Users can insert issue_comments" on public.issue_comments for insert with check (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can update issue_comments') then
    create policy "Users can update issue_comments" on public.issue_comments for update using (auth.role() = 'authenticated');
  end if;
end;
$$;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'issue_comments' and policyname = 'Users can delete issue_comments') then
    create policy "Users can delete issue_comments" on public.issue_comments for delete using (auth.role() = 'authenticated');
  end if;
end;
$$;

create index if not exists idx_issue_comments_issue on public.issue_comments(issue_id);

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'issue_comments_updated_at'
  ) then
    create trigger issue_comments_updated_at
      before update on public.issue_comments
      for each row
      execute function extensions.moddatetime(updated_at);
  end if;
end;
$$;
